name: focus_day
description: Una aplicación móvil de productividad para organizar tareas y mantener el enfoque.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^9.2.0
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utilities
  intl: ^0.20.2
  
  # Notifications
  flutter_local_notifications: ^19.5.0

  # UI
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
